spring.application.name=category-service

server.port=8088

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/categorydb
spring.datasource.username=user
spring.datasource.password=user123

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Eureka Configuration
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

#config client configuration
spring.config.import=configserver:http://localhost:9096

spring.profiles.active=prod

